
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

create-package: ## Create wheel and tar gz
	rm -rf dist/
	python setup.py bdist_wheel --plat-name=manylinux1_x86_64
	python setup.py sdist
	python -m twine upload  dist/* --verbose --skip-existing

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run not slow tests
	pytest -k "not slow"

test-full: ## Run all tests
	pytest

train-ljspeech: ## Train the model
	python matcha/train.py experiment=ljspeech

train-ljspeech-min: ## Train the model with minimum memory
	python matcha/train.py experiment=ljspeech_min_memory

start_app: ## Start the app
	python matcha/app.py

# ---------- TTS web app (FastAPI + SvelteKit) ----------
VENV ?= venv
PY := $(VENV)/bin/python
API_PORT ?= 8000
WEB_PORT ?= 5173

install: ## Install backend (editable) and frontend dependencies
	$(PY) -m pip install -e . --no-deps
	$(PY) -m pip install fastapi uvicorn
	cd web && bun install

backend: ## Start FastAPI TTS server (http://localhost:8000/docs)
	$(PY) -m uvicorn server.main:app --host 0.0.0.0 --port $(API_PORT) --reload --reload-dir server

frontend: ## Start SvelteKit dev server (http://localhost:5173)
	cd web && bun run dev --port $(WEB_PORT)

dev: ## Start backend and frontend together (Ctrl+C stops both)
	@$(MAKE) -j2 backend frontend

.PHONY: help clean install backend frontend dev
